"""
Test V4 system prompt on 5 diverse MedReason examples.

Verifies:
1. Ground truth answer is PRESERVED (hard constraint)
2. Reasoning is mechanistically deeper than original
3. Longevity framing is NOT applied to anatomy/basic science
4. Self-verification: independent model can reach correct answer from reasoning alone
5. No factual errors introduced

Usage:
    python3 scripts/test_v4_prompt.py
    python3 scripts/test_v4_prompt.py --verify  # adds self-verification pass
"""

import json
import subprocess
import sys
import re
import time
from pathlib import Path

INPUT_FILE = Path("docs/datasets/medreason_32k.jsonl")
OUTPUT_DIR = Path("docs/datasets/upgraded")

# --- V4 SYSTEM PROMPT ---

V4_SYSTEM = """You are a world-class physician-scientist with deep expertise in clinical medicine,
pathophysiology, and precision/preventive medicine. You are upgrading medical reasoning
traces originally generated by GPT-4o using a knowledge graph (PrimeKG).

TASK: Produce an upgraded chain-of-thought that reaches the SAME ground-truth answer,
but with stronger, more mechanistic clinical reasoning.

HARD GUARDRAILS:
1. THE ANSWER MUST BE THE GROUND TRUTH PROVIDED. You are refining the REASONING PATH,
   never the answer. If your reasoning leads elsewhere, backtrack and find the mechanistic
   path to the correct answer.
2. DO NOT introduce factual errors or false precision. Distinguish between settled
   pathophysiology and observational data.
3. MATCH MODE TO DOMAIN:
   - Anatomy/Histology: Focus on structural relationships, fascial planes, and embryology.
   - Pharmacology: Focus on MoA, receptor kinetics, and side-effect mechanisms.
   - Clinical Vignette: Focus on pivotal findings, pathophysiology, and population-specific
     nuances (age/sex/comorbidities).
   - Diagnostics: Focus on sensitivity/specificity, test characteristics, timing.
   - Basic Science: Focus on metabolic pathways or molecular signaling.
4. PRESERVE KG logic from the original reasoning when accurate, but translate it into
   natural, dense clinical prose.

UPGRADE DIMENSIONS:
- Mechanistic Depth: Move beyond pattern matching. WHY does this finding occur at the
  cellular or physiological level?
- Differential Calibration: Contrast the correct answer against 1-2 highly relevant
  differentials. State the specific negative finding or clinical pearl that rules them out.
- Preventive/Longevity Lens (CONDITIONAL): ONLY if the question involves chronic disease,
  metabolic/CV health, cancer, or aging, add a note on upstream modifiable drivers or
  optimal vs normal ranges. If it is an anatomy/microbiology/acute trauma question, OMIT THIS.
- Evidence Assessment: Use GRADE-style certainty when citing guidelines
  (e.g., "High-certainty evidence supports..." or "Per guidelines [Grade B]...").
- Contradiction Resolution: If the original reasoning was conflicted, resolve it by
  prioritizing the most definitive clinical finding.

FORMAT (STRICT):
<reasoning>
[5-15 sentences of dense, mechanistic clinical reasoning.
Start with the pivotal finding -> work through the pathophysiology -> contrast with
1-2 differentials -> conclude with why the answer is definitive.
Add population/longevity context ONLY if domain-appropriate.]
</reasoning>
<answer>[Letter]. [Answer text]</answer>

ANTI-PATTERNS:
- No filler ("Let's analyze...", "Interestingly", "Let me think...").
- No forcing longevity/metabolic framing on non-metabolic questions.
- No changing the answer under any circumstance.
- No restating the question text.
- No presenting observational evidence as definitive."""

VERIFY_SYSTEM = """You are a medical examiner verifying reasoning quality. Given ONLY the reasoning below
(NOT the original question's ground truth), determine what answer the reasoning supports.
You must pick from the provided options. Output ONLY the letter."""

QUALITY_CHECK_SYSTEM = """You are a medical education quality auditor. Evaluate this upgraded reasoning trace.

Score each dimension 1-5:
1. ANSWER_PRESERVED: Does the reasoning lead to the stated answer? (5=definitively, 1=contradicts)
2. FACTUAL_ACCURACY: Are all medical claims accurate? (5=flawless, 1=contains errors)
3. MECHANISTIC_DEPTH: Does it explain WHY, not just WHAT? (5=deep mechanism, 1=surface pattern)
4. DIFFERENTIAL_QUALITY: Are alternatives genuinely considered and ruled out? (5=excellent, 1=absent)
5. DOMAIN_APPROPRIATENESS: Is the framing matched to the question type? (5=perfect match, 1=forced irrelevant framing)
6. LONGEVITY_APPROPRIATENESS: If longevity content present, is it relevant? If absent on a basic science Q, that's correct. (5=perfectly calibrated, 1=forced/missing when needed)
7. CONCISENESS: Dense signal, no filler? (5=every word counts, 1=padded/verbose)

Output as JSON:
{"scores": {"answer_preserved": N, "factual_accuracy": N, "mechanistic_depth": N, "differential_quality": N, "domain_appropriateness": N, "longevity_appropriateness": N, "conciseness": N}, "issues": ["list any problems"], "verdict": "PASS" or "FAIL"}

A FAIL means the upgraded reasoning is WORSE than original or changes the answer."""


def get_test_examples():
    """Get 5 diverse examples from different source datasets."""
    examples = []
    seen = set()
    targets = ['medqa', 'medmcqa', 'pubmedqa', 'huatuo', 'MMLU']

    with open(INPUT_FILE) as f:
        for line in f:
            ex = json.loads(line)
            if ex['dataset_name'] in targets and ex['dataset_name'] not in seen:
                seen.add(ex['dataset_name'])
                examples.append(ex)
            if len(examples) == 5:
                break

    return examples


def extract_gt_letter(answer_text):
    """Extract ground truth letter from answer field."""
    for char in answer_text:
        if char in "ABCDE":
            return char
    # For yes/no questions
    lower = answer_text.lower()
    if "yes" in lower:
        return "A"
    if "no" in lower:
        return "B"
    return ""


def call_codex(prompt, suffix=""):
    """Call GPT-5.4 via Codex CLI."""
    ts = int(time.time())
    prompt_file = Path(f"/tmp/v4test-prompt-{ts}{suffix}.md")
    output_file = Path(f"/tmp/v4test-output-{ts}{suffix}.md")

    prompt_file.write_text(prompt)

    result = subprocess.run(
        [
            "codex", "exec", "-m", "gpt-5.4",
            "--skip-git-repo-check",
            "--sandbox", "read-only",
            "--ephemeral",
            "-c", "model_reasoning_effort=xhigh",
            "-o", str(output_file),
            "-",
        ],
        stdin=open(prompt_file),
        capture_output=True,
        text=True,
        timeout=180,
    )

    if output_file.exists():
        return output_file.read_text()
    return result.stdout


def upgrade_single(example):
    """Upgrade a single example using v4 prompt."""
    gt_letter = extract_gt_letter(example["answer"])

    prompt = f"""{V4_SYSTEM}

Upgrade the following example. Ground truth answer: {gt_letter}

Question: {example['question']}
Options: {example['options']}
Ground Truth Answer: {gt_letter}

Original Reasoning (GPT-4o + PrimeKG):
{example['reasoning']}

Produce your upgraded <reasoning> and <answer> now."""

    return call_codex(prompt, f"-ex{example['dataset_name']}")


def verify_answer(question, options, reasoning):
    """Self-verification: can a model reach the correct answer from reasoning alone?"""
    prompt = f"""{VERIFY_SYSTEM}

Question: {question}
Options: {options}

Reasoning provided:
{reasoning}

Based ONLY on the reasoning above, the answer is:"""

    return call_codex(prompt, "-verify").strip()


def quality_check(example, upgraded_reasoning, upgraded_answer):
    """Run quality audit on upgraded reasoning."""
    gt_letter = extract_gt_letter(example["answer"])

    prompt = f"""{QUALITY_CHECK_SYSTEM}

ORIGINAL QUESTION: {example['question']}
OPTIONS: {example['options']}
GROUND TRUTH: {gt_letter}
DATASET SOURCE: {example['dataset_name']}

ORIGINAL REASONING (GPT-4o):
{example['reasoning'][:800]}

UPGRADED REASONING:
{upgraded_reasoning}

UPGRADED ANSWER: {upgraded_answer}

Evaluate now. Output JSON only."""

    return call_codex(prompt, "-quality")


def parse_response(raw):
    """Parse <reasoning> and <answer> from response."""
    reasoning_match = re.search(r'<reasoning>(.*?)</reasoning>', raw, re.DOTALL)
    answer_match = re.search(r'<answer>(.*?)</answer>', raw, re.DOTALL)

    reasoning = reasoning_match.group(1).strip() if reasoning_match else ""
    answer = answer_match.group(1).strip() if answer_match else ""

    return reasoning, answer


def main():
    verify = "--verify" in sys.argv

    print("=" * 70)
    print("V4 SYSTEM PROMPT TEST — 5 Diverse MedReason Examples")
    print("=" * 70)

    examples = get_test_examples()
    print(f"\nLoaded {len(examples)} test examples:")
    for i, ex in enumerate(examples):
        gt = extract_gt_letter(ex["answer"])
        print(f"  {i+1}. [{ex['dataset_name']}] GT={gt} — {ex['question'][:60]}...")

    results = []

    for i, ex in enumerate(examples):
        gt_letter = extract_gt_letter(ex["answer"])
        print(f"\n{'='*70}")
        print(f"EXAMPLE {i+1}/{len(examples)}: [{ex['dataset_name']}] GT={gt_letter}")
        print(f"Q: {ex['question'][:100]}...")
        print(f"{'='*70}")

        # Step 1: Upgrade
        print("\n[1/3] Upgrading reasoning with v4 prompt...")
        try:
            raw = upgrade_single(ex)
            reasoning, answer = parse_response(raw)

            if not reasoning:
                print("  ERROR: No <reasoning> block found in output")
                print(f"  Raw output: {raw[:500]}")
                results.append({"example": i+1, "status": "PARSE_ERROR"})
                continue

            # Check answer preservation
            upgraded_letter = answer[0] if answer and answer[0] in "ABCDE" else ""
            answer_preserved = upgraded_letter == gt_letter

            print(f"  Upgraded answer: {upgraded_letter} (GT: {gt_letter}) — {'MATCH' if answer_preserved else 'MISMATCH!'}")
            print(f"  Reasoning length: {len(reasoning)} chars ({len(reasoning.split())} words)")
            print(f"\n  UPGRADED REASONING:")
            for line in reasoning.split('\n'):
                print(f"    {line}")
            print(f"\n  UPGRADED ANSWER: {answer}")

            if not answer_preserved:
                print("\n  *** CRITICAL: ANSWER CHANGED! This is a HARD FAILURE. ***")

        except subprocess.TimeoutExpired:
            print("  TIMEOUT")
            results.append({"example": i+1, "status": "TIMEOUT"})
            continue
        except Exception as e:
            print(f"  ERROR: {e}")
            results.append({"example": i+1, "status": f"ERROR: {e}"})
            continue

        # Step 2: Self-verification
        if verify:
            print("\n[2/3] Self-verification (can reasoning alone reach GT?)...")
            try:
                verify_result = verify_answer(ex["question"], ex["options"], reasoning)
                verify_letter = verify_result[0] if verify_result and verify_result[0] in "ABCDE" else "?"
                verify_pass = verify_letter == gt_letter
                print(f"  Verification answer: {verify_letter} (GT: {gt_letter}) — {'PASS' if verify_pass else 'FAIL'}")
            except Exception as e:
                print(f"  Verification error: {e}")
                verify_pass = None
                verify_letter = "?"
        else:
            verify_pass = None
            verify_letter = "-"

        # Step 3: Quality audit
        print(f"\n[{'3' if verify else '2'}/{'3' if verify else '2'}] Quality audit...")
        try:
            quality_raw = quality_check(ex, reasoning, answer)
            print(f"  Quality assessment:")
            # Try to parse JSON from response
            json_match = re.search(r'\{.*\}', quality_raw, re.DOTALL)
            if json_match:
                quality = json.loads(json_match.group())
                scores = quality.get("scores", {})
                for k, v in scores.items():
                    bar = "█" * v + "░" * (5 - v)
                    print(f"    {k:30s} {bar} {v}/5")
                issues = quality.get("issues", [])
                if issues:
                    print(f"    Issues: {issues}")
                verdict = quality.get("verdict", "?")
                print(f"    VERDICT: {verdict}")
            else:
                print(f"    Raw: {quality_raw[:500]}")
                quality = {}
                verdict = "?"
        except Exception as e:
            print(f"  Quality check error: {e}")
            quality = {}
            verdict = "?"

        # Check for longevity framing on non-clinical questions
        longevity_keywords = ["longevity", "preventive", "aging", "modifiable", "risk factor",
                              "screening", "metabolic", "insulin", "inflammation"]
        has_longevity = any(kw in reasoning.lower() for kw in longevity_keywords)
        is_basic_science = ex["dataset_name"] in ["medmcqa"] and any(
            kw in ex["question"].lower() for kw in ["diaphragm", "anatomy", "histology", "embryology"]
        )

        if has_longevity and is_basic_science:
            print(f"\n  *** WARNING: Longevity framing detected on basic science question! ***")

        results.append({
            "example": i+1,
            "dataset": ex["dataset_name"],
            "gt_letter": gt_letter,
            "upgraded_letter": upgraded_letter,
            "answer_preserved": answer_preserved,
            "verify_pass": verify_pass,
            "verify_letter": verify_letter,
            "reasoning_length": len(reasoning),
            "original_length": len(ex["reasoning"]),
            "quality": quality,
            "verdict": verdict,
            "has_longevity_framing": has_longevity,
            "is_basic_science": is_basic_science,
            "status": "OK",
        })

    # Summary
    print(f"\n{'='*70}")
    print("SUMMARY")
    print(f"{'='*70}")

    ok = [r for r in results if r.get("status") == "OK"]
    print(f"Processed: {len(ok)}/{len(examples)}")
    print(f"Answer preserved: {sum(1 for r in ok if r.get('answer_preserved'))}/{len(ok)}")
    if verify:
        verified = [r for r in ok if r.get("verify_pass") is not None]
        print(f"Self-verified: {sum(1 for r in verified if r['verify_pass'])}/{len(verified)}")
    print(f"Quality PASS: {sum(1 for r in ok if r.get('verdict') == 'PASS')}/{len(ok)}")
    print(f"Inappropriate longevity: {sum(1 for r in ok if r.get('has_longevity_framing') and r.get('is_basic_science'))}/{len(ok)}")

    avg_compression = sum(r["reasoning_length"] / max(1, r["original_length"]) for r in ok) / max(1, len(ok))
    print(f"Avg reasoning compression: {avg_compression:.1%} of original")

    # Save results
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_file = OUTPUT_DIR / "v4_test_results.json"
    with open(output_file, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nResults saved to: {output_file}")

    # Final verdict
    all_preserved = all(r.get("answer_preserved") for r in ok)
    no_bad_framing = not any(r.get("has_longevity_framing") and r.get("is_basic_science") for r in ok)

    if all_preserved and no_bad_framing:
        print("\n✓ V4 PROMPT PASSED ALL GUARDRAILS")
    else:
        if not all_preserved:
            print("\n✗ CRITICAL: Some answers were changed!")
        if not no_bad_framing:
            print("\n✗ WARNING: Inappropriate longevity framing detected")


if __name__ == "__main__":
    main()
