"""
Upgrade MedReason examples in batches by dataset type.

Processes N examples from each dataset type, verifies answer preservation,
and logs completed IDs to prevent duplicate processing.

Usage:
    python3 scripts/upgrade_batch.py --per-type 10
    python3 scripts/upgrade_batch.py --per-type 10 --dry-run
"""

import json
import subprocess
import sys
import re
import time
from pathlib import Path
from datetime import datetime, timezone

INPUT_FILE = Path("docs/datasets/medreason_32k.jsonl")
OUTPUT_DIR = Path("docs/datasets/upgraded")
LOG_FILE = OUTPUT_DIR / "upgrade_log.jsonl"
OUTPUT_FILE = OUTPUT_DIR / "v41_upgraded.jsonl"
FAILED_FILE = OUTPUT_DIR / "v41_failed.jsonl"

V41_SYSTEM = """You are a world-class physician-scientist with deep expertise in clinical medicine,
pathophysiology, and precision/preventive medicine. You are upgrading medical reasoning
traces originally generated by GPT-4o using a knowledge graph (PrimeKG).

TASK: Produce an upgraded chain-of-thought that reaches the SAME ground-truth answer,
but with stronger, more mechanistic clinical reasoning.

HARD GUARDRAILS:
1. THE ANSWER MUST BE THE GROUND TRUTH PROVIDED. You are refining the REASONING PATH,
   never the answer. If your reasoning leads elsewhere, backtrack and find the mechanistic
   path to the correct answer.
2. DO NOT introduce factual errors or false precision. Distinguish between settled
   pathophysiology and observational data.
3. MATCH MODE TO DOMAIN:
   - Anatomy/Histology: Focus on structural relationships, fascial planes, and embryology.
   - Pharmacology: Focus on MoA, receptor kinetics, and side-effect mechanisms.
   - Clinical Vignette: Focus on pivotal findings, pathophysiology, and population-specific
     nuances (age/sex/comorbidities).
   - Diagnostics: Focus on sensitivity/specificity, test characteristics, timing.
   - Basic Science: Focus on metabolic pathways or molecular signaling.
4. PRESERVE KG logic from the original reasoning when accurate, but translate it into
   natural, dense clinical prose.

UPGRADE DIMENSIONS:
- Mechanistic Depth: Move beyond pattern matching. WHY does this finding occur at the
  cellular or physiological level?
- Differential Calibration: Contrast the correct answer against 1-2 highly relevant
  differentials. State the specific negative finding or clinical pearl that rules them out.
- Preventive/Longevity Lens (CONDITIONAL): ONLY if the question involves chronic disease,
  metabolic/CV health, cancer, or aging, add a note on upstream modifiable drivers or
  optimal vs normal ranges. If it is an anatomy/microbiology/acute trauma question, OMIT THIS.
- Evidence Assessment: Use GRADE-style certainty when citing guidelines
  (e.g., "High-certainty evidence supports..." or "Per guidelines [Grade B]...").
- Contradiction Resolution: If the original reasoning was conflicted, resolve it by
  prioritizing the most definitive clinical finding.

FORMAT (STRICT):
<reasoning>
[5-15 sentences of dense, mechanistic clinical reasoning.
Start with the pivotal finding -> work through the pathophysiology -> contrast with
1-2 differentials -> conclude with why the answer is definitive.
Add population/longevity context ONLY if domain-appropriate.]
</reasoning>
<answer>[Letter]. [Answer text]</answer>

ANTI-PATTERNS:
- No filler ("Let's analyze...", "Interestingly", "Let me think...").
- No forcing longevity/metabolic framing on non-metabolic questions.
- No changing the answer under any circumstance.
- No restating the question text.
- No presenting observational evidence as definitive."""

VERIFY_SYSTEM = """You are a medical examiner. Given ONLY the reasoning below, determine the answer
to the question. You must pick from the provided options. Output ONLY the letter."""


def load_completed_ids():
    """Load set of already-processed example IDs from log."""
    completed = set()
    if LOG_FILE.exists():
        with open(LOG_FILE) as f:
            for line in f:
                try:
                    entry = json.loads(line)
                    completed.add(entry["id"])
                except (json.JSONDecodeError, KeyError):
                    continue
    return completed


def make_example_id(ex):
    """Create unique ID for an example."""
    return f"{ex['dataset_name']}:{ex['id_in_dataset']}"


def extract_gt_letter(example):
    """Extract ground truth letter from answer field, matching against options if needed."""
    answer_text = example["answer"]
    options_text = example.get("options", "")

    # 1. Direct letter prefix: "B. Small cell..." or "(E) Iliolumbar..."
    m = re.match(r'^\(?([A-E])\)?[\.\)]?\s', answer_text)
    if m:
        return m.group(1)

    # 2. "The final decision is: yes/no" (pubmedqa variants)
    lower = answer_text.lower()
    if "the final decision is: yes" in lower or lower.startswith("yes"):
        return "A"
    if "the final decision is: no" in lower or lower.startswith("no"):
        return "B"

    # 3. Match answer text against options to find the letter
    if options_text:
        # Parse options like "A. Deep transverse\nB. Perinial membrane\n..."
        option_matches = re.findall(r'([A-E])[\.\)]\s*(.+?)(?=\n[A-E][\.\)]|\Z)', options_text, re.DOTALL)
        if not option_matches:
            # Try "Answer Choices:\nA. ..."
            option_matches = re.findall(r'([A-E])[\.\)]\s*(.+?)(?=\n[A-E][\.\)]|\Z)',
                                         options_text.replace("Answer Choices:\n", ""), re.DOTALL)

        answer_lower = answer_text.lower().strip().rstrip('.')
        for letter, text in option_matches:
            opt_lower = text.strip().lower().rstrip('.')
            # Check if answer starts with the option text or vice versa
            if answer_lower.startswith(opt_lower[:30]) or opt_lower.startswith(answer_lower[:30]):
                return letter

    # 4. Last resort: first letter A-E in the text
    for char in answer_text:
        if char in "ABCDE":
            return char

    return ""


def select_examples(per_type=10):
    """Select N examples from each dataset type, skipping already completed."""
    completed = load_completed_ids()
    print(f"Already completed: {len(completed)} examples")

    from collections import defaultdict
    by_type = defaultdict(list)

    with open(INPUT_FILE) as f:
        for line in f:
            ex = json.loads(line)
            eid = make_example_id(ex)
            if eid in completed:
                continue
            ds = ex["dataset_name"]
            if len(by_type[ds]) < per_type:
                by_type[ds].append(ex)

    selected = []
    for ds in sorted(by_type.keys()):
        n = len(by_type[ds])
        selected.extend(by_type[ds])
        print(f"  {ds:25s}: {n} selected")

    print(f"Total to process: {len(selected)}")
    return selected


def call_model(prompt, suffix=""):
    """Call Gemini via CLI. Falls back to Codex if available."""
    ts = int(time.time())
    prompt_file = Path(f"/tmp/upgrade-{ts}{suffix}.md")
    prompt_file.write_text(prompt)

    # Try Gemini first (auto-routes to gemini-3.1-pro-preview)
    try:
        # Pass prompt via stdin to avoid shell argument length limits
        result = subprocess.run(
            ["gemini", "-y"],
            input=prompt,
            capture_output=True,
            text=True,
            timeout=180,
        )
        output = result.stdout.strip()
        if output:
            return output, "gemini"
    except subprocess.TimeoutExpired:
        print(f"    gemini timed out")
    except Exception as e:
        print(f"    gemini error: {e}")

    # Fallback to Codex
    output_file = Path(f"/tmp/upgrade-out-{ts}{suffix}.md")
    for model in ["gpt-5.4", "gpt-5.3-codex"]:
        try:
            result = subprocess.run(
                [
                    "codex", "exec", "-m", model,
                    "--skip-git-repo-check",
                    "--sandbox", "read-only",
                    "--ephemeral",
                    "-c", "model_reasoning_effort=xhigh",
                    "-o", str(output_file),
                    "-",
                ],
                stdin=open(prompt_file),
                capture_output=True,
                text=True,
                timeout=180,
            )
            if output_file.exists():
                content = output_file.read_text().strip()
                if content and "usage limit" not in content.lower():
                    return content, model
        except Exception:
            continue

    return None, None


def upgrade_single(example):
    """Upgrade a single example using v4.1 prompt."""
    gt_letter = extract_gt_letter(example)
    if not gt_letter:
        return None, None, "no_gt_letter"

    prompt = f"""{V41_SYSTEM}

Upgrade the following example. Ground truth answer: {gt_letter}

Question: {example['question']}
Options: {example['options']}
Ground Truth Answer: {gt_letter}

Original Reasoning (GPT-4o + PrimeKG):
{example['reasoning'][:1500]}

Produce your upgraded <reasoning> and <answer> now."""

    raw, model = call_model(prompt, f"-{example['dataset_name']}")
    if not raw:
        return None, None, "api_failure"

    # Parse
    reasoning_match = re.search(r'<reasoning>(.*?)</reasoning>', raw, re.DOTALL)
    answer_match = re.search(r'<answer>(.*?)</answer>', raw, re.DOTALL)

    if not reasoning_match or not answer_match:
        return None, model, "parse_failure"

    reasoning = reasoning_match.group(1).strip()
    answer = answer_match.group(1).strip()

    # Verify answer preserved
    upgraded_letter = ""
    for char in answer:
        if char in "ABCDE":
            upgraded_letter = char
            break

    if upgraded_letter != gt_letter:
        return {
            "reasoning": reasoning,
            "answer": answer,
            "upgraded_letter": upgraded_letter,
            "gt_letter": gt_letter,
        }, model, "answer_changed"

    return {
        "reasoning": reasoning,
        "answer": answer,
        "upgraded_letter": upgraded_letter,
        "gt_letter": gt_letter,
    }, model, "success"


def verify_reasoning(example, reasoning):
    """Self-verification: can reasoning alone produce correct answer?"""
    gt_letter = extract_gt_letter(example)

    prompt = f"""{VERIFY_SYSTEM}

Question: {example['question']}
Options: {example['options']}

Reasoning provided:
{reasoning}

Based ONLY on the reasoning above, the answer is:"""

    raw, _ = call_model(prompt, "-verify")
    if not raw:
        return None

    raw = raw.strip()
    for char in raw:
        if char in "ABCDE":
            return char
    return None


def log_entry(example, status, result=None, model=None, verified=None):
    """Append to upgrade log."""
    entry = {
        "id": make_example_id(example),
        "dataset": example["dataset_name"],
        "id_in_dataset": example["id_in_dataset"],
        "status": status,
        "model": model,
        "verified": verified,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    with open(LOG_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")


def save_upgraded(example, result):
    """Append upgraded example to output JSONL."""
    gt_letter = extract_gt_letter(example)
    entry = {
        "messages": [
            {"role": "user", "content": f"{example['question']}\n\n{example['options']}\n\nAnswer:"},
            {"role": "assistant", "content": f"<think>\n{result['reasoning']}\n</think>\n{result['answer']}"},
        ],
        "metadata": {
            "source": example["dataset_name"],
            "source_id": example["id_in_dataset"],
            "ground_truth": gt_letter,
            "original_reasoning_len": len(example["reasoning"]),
            "upgraded_reasoning_len": len(result["reasoning"]),
        },
    }
    with open(OUTPUT_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")


def save_failed(example, result, reason):
    """Log failed upgrades for review."""
    entry = {
        "id": make_example_id(example),
        "dataset": example["dataset_name"],
        "question": example["question"][:200],
        "reason": reason,
        "gt_letter": extract_gt_letter(example),
        "upgraded_letter": result.get("upgraded_letter") if result else None,
    }
    with open(FAILED_FILE, "a") as f:
        f.write(json.dumps(entry) + "\n")


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--per-type", type=int, default=10)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--no-verify", action="store_true")
    args = parser.parse_args()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("=" * 70)
    print(f"MedReason V4.1 Upgrade — {args.per_type} per dataset type")
    print("=" * 70)

    examples = select_examples(args.per_type)

    if args.dry_run:
        print("\n[DRY RUN] Would process the above examples. Exiting.")
        return

    if not examples:
        print("\nNo examples to process (all already completed).")
        return

    stats = {"success": 0, "answer_changed": 0, "parse_failure": 0,
             "api_failure": 0, "no_gt_letter": 0, "verify_fail": 0}

    for i, ex in enumerate(examples):
        eid = make_example_id(ex)
        gt = extract_gt_letter(ex)
        print(f"\n[{i+1}/{len(examples)}] {eid} (GT={gt})")
        print(f"  Q: {ex['question'][:80]}...")

        result, model, status = upgrade_single(ex)

        if status == "success":
            # Self-verification
            verified = None
            if not args.no_verify:
                print(f"  Upgraded ({model}). Verifying...")
                v_letter = verify_reasoning(ex, result["reasoning"])
                verified = v_letter == gt if v_letter else None
                if verified:
                    print(f"  Verified: {v_letter} = {gt}")
                elif v_letter:
                    print(f"  VERIFY FAIL: {v_letter} != {gt} — discarding")
                    stats["verify_fail"] += 1
                    log_entry(ex, "verify_fail", result, model, False)
                    save_failed(ex, result, "verify_fail")
                    continue
                else:
                    print(f"  Verification inconclusive (API issue), keeping")

            stats["success"] += 1
            save_upgraded(ex, result)
            log_entry(ex, "success", result, model, verified)
            print(f"  SAVED ({len(result['reasoning'])} chars)")

        elif status == "answer_changed":
            print(f"  ANSWER CHANGED: {result['upgraded_letter']} != {gt} — discarding")
            stats["answer_changed"] += 1
            log_entry(ex, "answer_changed", result, model)
            save_failed(ex, result, "answer_changed")

        else:
            print(f"  FAILED: {status}")
            stats[status] += 1
            log_entry(ex, status, model=model)

        # Brief pause to avoid rate limits
        time.sleep(1)

    # Summary
    print(f"\n{'=' * 70}")
    print("UPGRADE SUMMARY")
    print(f"{'=' * 70}")
    for k, v in stats.items():
        print(f"  {k:20s}: {v}")
    print(f"  {'TOTAL':20s}: {sum(stats.values())}")

    total_completed = len(load_completed_ids())
    print(f"\nCumulative completed: {total_completed}")
    if OUTPUT_FILE.exists():
        with open(OUTPUT_FILE) as f:
            n_upgraded = sum(1 for _ in f)
        print(f"Total upgraded examples: {n_upgraded}")
    print(f"Output: {OUTPUT_FILE}")
    print(f"Log: {LOG_FILE}")


if __name__ == "__main__":
    main()
