"""
Upgrade MedReason 32K with GPT-5.4 reasoning.

MedReason was generated by GPT-4o + PrimeKG knowledge graph.
This script upgrades it with GPT-5.4's superior reasoning:

Pipeline:
  1. Load MedReason examples
  2. For each example, send question + KG paths to GPT-5.4
  3. GPT-5.4 re-reasons with deeper clinical depth
  4. Self-verify: GPT-5.4 re-answers from its own reasoning
  5. Compare with ground truth, keep only correct
  6. Format as <think> for Qwen 3.5 training

Usage:
    python3 scripts/upgrade_medreason.py --count 100 --batch-size 5
    python3 scripts/upgrade_medreason.py --count 5000 --batch-size 10 --domain longevity
"""

import json
import subprocess
import sys
import time
import re
from pathlib import Path

INPUT_FILE = Path("docs/datasets/medreason_32k.jsonl")
OUTPUT_DIR = Path("docs/datasets/upgraded")

# --- PROMPTS ---

UPGRADE_SYSTEM = """You are a world-class physician-scientist with deep expertise in clinical medicine,
pathophysiology, and precision/preventive medicine. You are upgrading medical reasoning
traces originally generated by GPT-4o using a knowledge graph (PrimeKG).

TASK: Produce an upgraded chain-of-thought that reaches the SAME ground-truth answer,
but with stronger, more mechanistic clinical reasoning.

HARD GUARDRAILS:
1. THE ANSWER MUST BE THE GROUND TRUTH PROVIDED. You are refining the REASONING PATH,
   never the answer. If your reasoning leads elsewhere, backtrack and find the mechanistic
   path to the correct answer.
2. DO NOT introduce factual errors or false precision. Distinguish between settled
   pathophysiology and observational data.
3. MATCH MODE TO DOMAIN:
   - Anatomy/Histology: Focus on structural relationships, fascial planes, and embryology.
   - Pharmacology: Focus on MoA, receptor kinetics, and side-effect mechanisms.
   - Clinical Vignette: Focus on pivotal findings, pathophysiology, and population-specific
     nuances (age/sex/comorbidities).
   - Diagnostics: Focus on sensitivity/specificity, test characteristics, timing.
   - Basic Science: Focus on metabolic pathways or molecular signaling.
4. PRESERVE KG logic from the original reasoning when accurate, but translate it into
   natural, dense clinical prose.

UPGRADE DIMENSIONS:
- Mechanistic Depth: Move beyond pattern matching. WHY does this finding occur at the
  cellular or physiological level?
- Differential Calibration: Contrast the correct answer against 1-2 highly relevant
  differentials. State the specific negative finding or clinical pearl that rules them out.
- Preventive/Longevity Lens (CONDITIONAL): ONLY if the question involves chronic disease,
  metabolic/CV health, cancer, or aging, add a note on upstream modifiable drivers or
  optimal vs normal ranges. If it is an anatomy/microbiology/acute trauma question, OMIT THIS.
- Evidence Assessment: Use GRADE-style certainty when citing guidelines
  (e.g., "High-certainty evidence supports..." or "Per guidelines [Grade B]...").
- Contradiction Resolution: If the original reasoning was conflicted, resolve it by
  prioritizing the most definitive clinical finding.

FORMAT (STRICT):
<reasoning>
[5-15 sentences of dense, mechanistic clinical reasoning.
Start with the pivotal finding -> work through the pathophysiology -> contrast with
1-2 differentials -> conclude with why the answer is definitive.
Add population/longevity context ONLY if domain-appropriate.]
</reasoning>
<answer>[Letter]. [Answer text]</answer>

ANTI-PATTERNS:
- No filler ("Let's analyze...", "Interestingly", "Let me think...").
- No forcing longevity/metabolic framing on non-metabolic questions.
- No changing the answer under any circumstance.
- No restating the question text.
- No presenting observational evidence as definitive."""

VERIFY_SYSTEM = """You are a medical examiner. Given ONLY the reasoning below, determine the answer
to the question. You must pick from the provided options. Output ONLY the letter."""


def load_medreason(count=100, domain=None):
    """Load MedReason examples, optionally filtered by domain keywords."""
    examples = []
    domain_keywords = {
        "longevity": ["aging", "age-related", "elderly", "geriatric", "senescence",
                       "telomere", "epigenetic", "biological age", "longevity",
                       "frailty", "sarcopenia", "osteoporosis", "dementia",
                       "alzheimer", "parkinson", "cardiovascular", "atherosclerosis"],
        "preventive": ["screening", "prevention", "prophylaxis", "vaccination",
                        "risk factor", "lifestyle", "diet", "exercise", "obesity",
                        "metabolic", "diabetes", "hypertension", "cholesterol",
                        "smoking", "alcohol"],
        "regenerative": ["stem cell", "growth factor", "wound healing", "tissue repair",
                          "regenerat", "peptide", "hormone", "testosterone",
                          "thyroid", "cortisol", "insulin", "IGF"],
    }

    keywords = domain_keywords.get(domain, []) if domain else []

    with open(INPUT_FILE) as f:
        for line in f:
            item = json.loads(line)
            if keywords:
                text = (item["question"] + " " + item["answer"] + " " + item["reasoning"]).lower()
                if not any(kw in text for kw in keywords):
                    continue
            examples.append(item)
            if len(examples) >= count:
                break

    return examples


def build_upgrade_prompt(examples):
    """Build a batch prompt for GPT-5.4 upgrade."""
    prompt = UPGRADE_SYSTEM + "\n\n"
    prompt += "Upgrade each example below. The ground-truth answer is provided — your reasoning must lead to it.\n\n"

    for i, ex in enumerate(examples):
        # Extract the correct answer letter from the answer field
        answer_letter = ""
        for char in ex["answer"]:
            if char in "ABCDE":
                answer_letter = char
                break

        prompt += f"--- EXAMPLE {i+1} ---\n"
        prompt += f"Question: {ex['question']}\n"
        prompt += f"Options: {ex['options']}\n"
        prompt += f"Ground Truth: {answer_letter}\n"
        prompt += f"Original Reasoning (GPT-4o + PrimeKG):\n{ex['reasoning'][:800]}\n\n"

    prompt += "--- END ---\n"
    prompt += "Provide upgraded <reasoning> and <answer> for each example, numbered to match."
    return prompt


def build_verify_prompt(question, options, reasoning):
    """Build a verification prompt — can the reasoning alone produce the right answer?"""
    return f"""{VERIFY_SYSTEM}

Question: {question}
Options: {options}

Reasoning provided:
{reasoning}

Based ONLY on the reasoning above, the answer is:"""


def call_gpt54(prompt, output_suffix=""):
    """Call GPT-5.4 via Codex CLI."""
    ts = int(time.time())
    prompt_file = Path(f"/tmp/upgrade-prompt-{ts}{output_suffix}.md")
    output_file = Path(f"/tmp/upgrade-output-{ts}{output_suffix}.md")

    prompt_file.write_text(prompt)

    result = subprocess.run(
        [
            "codex", "exec", "-m", "gpt-5.4",
            "--skip-git-repo-check",
            "--sandbox", "read-only",
            "--ephemeral",
            "-c", "model_reasoning_effort=xhigh",
            "-o", str(output_file),
            "-",
        ],
        stdin=open(prompt_file),
        capture_output=True,
        text=True,
        timeout=300,
    )

    if output_file.exists():
        return output_file.read_text()
    return result.stdout


def parse_upgraded_responses(raw_output, examples):
    """Parse GPT-5.4 upgraded reasoning into structured format."""
    results = []

    reasoning_blocks = re.findall(
        r'<reasoning>(.*?)</reasoning>', raw_output, re.DOTALL
    )
    answer_blocks = re.findall(
        r'<answer>(.*?)</answer>', raw_output, re.DOTALL
    )

    for i, ex in enumerate(examples):
        reasoning = reasoning_blocks[i].strip() if i < len(reasoning_blocks) else ""
        answer = answer_blocks[i].strip() if i < len(answer_blocks) else ""

        if not reasoning or not answer:
            continue

        # Extract ground truth letter
        gt_letter = ""
        for char in ex["answer"]:
            if char in "ABCDE":
                gt_letter = char
                break

        # Check if upgraded answer matches ground truth
        upgraded_letter = answer[0] if answer and answer[0] in "ABCDE" else ""
        correct = upgraded_letter == gt_letter

        results.append({
            "question": ex["question"],
            "options": ex["options"],
            "original_reasoning": ex["reasoning"],
            "upgraded_reasoning": reasoning,
            "answer": answer,
            "ground_truth": gt_letter,
            "correct": correct,
            "source": ex["dataset_name"],
            "source_id": ex["id_in_dataset"],
            # Training format
            "messages": [
                {"role": "user", "content": f"{ex['question']}\n\n{ex['options']}\n\nAnswer:"},
                {"role": "assistant", "content": f"<think>\n{reasoning}\n</think>\n{answer}"},
            ],
        })

    return results


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--count", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=5)
    parser.add_argument("--domain", type=str, default=None,
                        choices=["longevity", "preventive", "regenerative"],
                        help="Filter for domain-specific examples")
    parser.add_argument("--verify", action="store_true",
                        help="Run self-verification pass (slower but higher quality)")
    args = parser.parse_args()

    print(f"Loading {args.count} MedReason examples" +
          (f" (domain: {args.domain})" if args.domain else "") + "...")
    examples = load_medreason(args.count, args.domain)
    print(f"Loaded {len(examples)} examples")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    domain_suffix = f"_{args.domain}" if args.domain else ""
    output_file = OUTPUT_DIR / f"gpt54_upgraded{domain_suffix}.jsonl"
    metadata_file = OUTPUT_DIR / f"gpt54_upgraded{domain_suffix}_meta.json"

    all_results = []
    correct_count = 0

    for batch_start in range(0, len(examples), args.batch_size):
        batch = examples[batch_start:batch_start + args.batch_size]
        batch_num = batch_start // args.batch_size + 1
        total_batches = (len(examples) + args.batch_size - 1) // args.batch_size

        print(f"\nBatch {batch_num}/{total_batches} ({len(batch)} examples)...")

        try:
            prompt = build_upgrade_prompt(batch)
            raw = call_gpt54(prompt, f"-b{batch_num}")
            results = parse_upgraded_responses(raw, batch)

            for r in results:
                all_results.append(r)
                if r["correct"]:
                    correct_count += 1

            print(f"  Parsed {len(results)}/{len(batch)}, "
                  f"correct: {correct_count}/{len(all_results)}")

            # Save intermediate
            with open(output_file, "w") as f:
                for r in all_results:
                    f.write(json.dumps({"messages": r["messages"]}) + "\n")

        except subprocess.TimeoutExpired:
            print(f"  TIMEOUT on batch {batch_num}, skipping...")
        except Exception as e:
            print(f"  ERROR on batch {batch_num}: {e}")

    # Self-verification pass
    if args.verify and all_results:
        print(f"\n{'='*60}")
        print("Running self-verification pass...")
        verified = []
        for r in all_results:
            try:
                verify_prompt = build_verify_prompt(
                    r["question"], r["options"], r["upgraded_reasoning"]
                )
                verify_answer = call_gpt54(verify_prompt, "-verify").strip()
                verify_letter = verify_answer[0] if verify_answer and verify_answer[0] in "ABCDE" else ""
                if verify_letter == r["ground_truth"]:
                    verified.append(r)
            except Exception:
                pass  # Skip failures

        print(f"Verified: {len(verified)}/{len(all_results)} passed")
        all_results = verified
        correct_count = len(verified)

    # Final save
    with open(output_file, "w") as f:
        for r in all_results:
            f.write(json.dumps({"messages": r["messages"]}) + "\n")

    with open(metadata_file, "w") as f:
        json.dump({
            "total": len(all_results),
            "correct": correct_count,
            "accuracy": round(100 * correct_count / max(1, len(all_results)), 1),
            "domain": args.domain,
            "model": "gpt-5.4",
            "source": "MedReason (GPT-4o + PrimeKG) → upgraded",
            "pipeline": "GPT-5.4 re-reasoning with xhigh effort",
            "verified": args.verify,
        }, f, indent=2)

    print(f"\n{'='*60}")
    print(f"DONE: {len(all_results)} upgraded examples")
    print(f"Accuracy: {correct_count}/{len(all_results)} "
          f"({100*correct_count/max(1,len(all_results)):.1f}%)")
    print(f"Saved to: {output_file}")


if __name__ == "__main__":
    main()
